/*
 * Copyright 2008 Lars Heuer (heuer[at]semagia.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.tinytim.mio;

import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;

import org.tinytim.Version;
import org.xml.sax.Attributes;
import org.xml.sax.helpers.AttributesImpl;

/**
 * Simple SAX-alike XML writer.
 * 
 * @author Lars Heuer (heuer[at]semagia.com) <a href="http://www.semagia.com/">Semagia</a>
 * @version $Rev:$ - $Date:$
 */
final class XMLWriter {

    public static final Attributes EMPTY_ATTRS = new AttributesImpl(); 

    private static final char _NL = '\n';

    private OutputStreamWriter _out;

    private final String _encoding;
    
    XMLWriter(OutputStream out) throws IOException {
        this(out, "utf-8");
    }

    XMLWriter(OutputStream out, String encoding) throws IOException {
        _out = new OutputStreamWriter(out, encoding);
        _encoding = encoding;
    }

    /* (non-Javadoc)
     * @see org.xml.sax.DocumentHandler#startDocument()
     */
    public void startDocument() throws IOException {
        _out.write("<?xml version=\"1.0\" encoding=\"");
        _out.write(_encoding);
        _out.write("\" standalone=\"yes\"?>");
        newline();
        _out.write("<!-- Generated by tinyTiM v");
        _out.write(Version.RELEASE);
        _out.write(" - http://tinytim.sourceforge.net/ -->");
        newline();
    }

    /* (non-Javadoc)
     * @see org.xml.sax.DocumentHandler#endDocument()
     */
    public void endDocument() throws IOException {
        newline();
        try {
            _out.flush();
        }
        finally {
            _out = null;
        }
    }

    public void startElement(String name) throws IOException {
        startElement(name, EMPTY_ATTRS);
    }

    /* (non-Javadoc)
     * @see org.xml.sax.DocumentHandler#startElement(java.lang.String, org.xml.sax.AttributeList)
     */
    public void startElement(String name, Attributes attrs) throws IOException {
        _out.write('<');
        _out.write(name);
        _writeAttributes(attrs);
        _out.write('>');
    }

    /* (non-Javadoc)
     * @see org.xml.sax.DocumentHandler#endElement(java.lang.String)
     */
    public void endElement(String name) throws IOException {
        _out.write("</");
        _out.write(name);
        _out.write('>');
    }

    public void emptyElement(String name, Attributes attrs) throws IOException {
        _out.write('<');
        _out.write(name);
        _writeAttributes(attrs);
        _out.write("/>");
    }

    public void dataElement(String name, String data) throws IOException {
        dataElement(name, EMPTY_ATTRS, data);
    }

    public void dataElement(String name, Attributes attrs, String data) throws IOException {
        startElement(name, attrs);
        characters(data);
        endElement(name);
    }

    public void _writeAttributes(Attributes attrs) throws IOException {
        char[] chars;
        for (int i=0; i < attrs.getLength(); i++) {
            _out.write(' ');
            _out.write(attrs.getLocalName(i));
            _out.write("=\"");
            chars = attrs.getValue(i).toCharArray();
            _writeEscapedCharacters(chars, 0, chars.length, true);
            _out.write('"');
        }
    }

    /**
     * Writes a <tt>#x0A</tt> to the output.
     *
     * @throws IOException If an error occurs.
     */
    public void newline() throws IOException {
        _out.write(_NL);
    }

    /**
     * Writes the specified characters to the output.
     * 
     * The data is written according to the rules of canonicalized XML.
     *
     * @param data The data to write.
     * @throws IOException If an error occurs.
     */
    public void characters(final String data) throws IOException {
        char[] chars = data.toCharArray();
        characters(chars, 0, chars.length);
    }

    /* (non-Javadoc)
     * @see org.xml.sax.DocumentHandler#characters(char[], int, int)
     */
    public void characters(char[] chars, int start, int length) throws IOException {
        _writeEscapedCharacters(chars, start, length, false);
    }

    private void _writeEscapedCharacters(char[] ch, int start, int length,
            boolean attributeValue) throws IOException {
        for (int i = start; i < start + length; i++) {
            switch (ch[i]) {
            case '&':
                _out.write("&amp;");
                break;
            case '<':
                _out.write("&lt;");
                break;
            case '>':
                _out.write("&gt;");
                break;
            case '\"':
                if (attributeValue) {
                    _out.write("&quot;");
                }
                else {
                    _out.write('\"');
                }
                break;
            default:
                if (ch[i] > '\u007f') {
                    _out.write("&#");
                    _out.write(Integer.toString(ch[i]));
                    _out.write(';');
                }
                else {
                    _out.write(ch[i]);
                }
            }
        }
        
    }

}
